dataset: imagenet
model:
  enbable_robust: true
  n_rtokens: 10
  name: dinov3_vits16
results_dir: results/dinov3_vits16_10
run_name: dinov3_vits16 (10 tokens)
seed: 0
train:
  batch_size: 8
  checkpoint_freq: 50
  criterion: CosineSimilarity
  lr: 0.01
  max_steps: 100
  mode: max
  num_workers: 16
  optimizer: Adam
