dataset: imagenet
model:
  enbable_robust: true
  n_rtokens: 10
  name: dinov3_vits16
results_dir: results/dinov3_vits16
run_name: dinov3_vits16 - train robustness
seed: 0
train:
  batch_size: 8
  checkpoint_freq: 50
  criterion: CosineSimilarity
  lr: 0.001
  max_steps: 50
  mode: max
  num_workers: 16
  optimizer: Adam
