dataset: imagenet
model:
  enbable_robust: true
  n_rtokens: 20
  name: dinov2_vitb14
results_dir: results/dinov2_vitb14_20
run_name: dinov2_vitb14 (20 tokens)
seed: 0
train:
  batch_size: 8
  checkpoint_freq: 50
  criterion: CosineSimilarity
  lr: 0.001
  max_steps: 100
  mode: max
  num_workers: 16
  optimizer: Adam
