dataset: imagenet
model:
  enbable_robust: true
  n_rtokens: 1
  name: dinov2_vitb14
results_dir: results/dinov2_vitb14_1
run_name: dinov2_vitb14 (1 token)
seed: 0
train:
  batch_size: 8
  checkpoint_freq: 50
  criterion: CosineSimilarity
  lr: 0.001
  max_steps: 100
  mode: max
  num_workers: 16
  optimizer: Adam
